let colors = {
  // theme: 'defaultTheme', // required variable for caching!
  primary: '#fdfdfd',
  //Secondary: '#f0f0f0',
  secondary: '#fdfdfd',
  tertiary: '#d5f0ea',
  passive: '#d0d0d0',
  primaryText: '#31515E',
  secondaryText: '#96A6AE',
  tertiaryText: '#b0b0b0',
  disabled: '#AAADB7',
  neutral: '#FDFDFD',
  theme: '#2A59FE',
  stunning: '#fc9803',
  success: '#00942c',
  warning: '#f58442',
  danger: '#c90000',
  darkGlass: 'rgba(0,0,0,0.5)',
  gradientLeft: '#4FAFA8',
  gradientRight: '#D2EAE7',
  border: '#d5d5d5',
  gradientLeftLow: '#FFDE89',
  gradientRightLow: '#FFE6A6',
  gradientLeftMedium: '#F2B872',
  gradientRightMedium: '#FFDBAF',
  gradientLeftHigh: '#BB432E',
  gradientRightHigh: '#E98979',
};

export {colors};
